services:
  postgres:
    image: postgres:15
    container_name: bank-postgres
    restart: always

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bankdb

    ports:
      - "5432:5432"

    volumes:
      - ./data:/data

  adminer:
    image: adminer
    container_name: bank-adminer
    restart: always

    ports:
      - "8080:8080"